---
- name: delete user 
  hosts: nodes

  tasks:

    - name:
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: absent

      loop:
      - name: Alice
      - name: Bob
      - name: Carol

