---
- hosts: nodes

  tasks:

  - name: Populate service facts
    service_facts:

  - name: Check Apache state
    debug:
      msg: "Apache service is {{ansible_facts.services['httpd.service'].state}} and {{ansible_facts.services['httpd.service'].status}}"
