---
# tasks file for apache_deploy
  - name: install httpd
      yum: name=httpd state=latest

    - name: Copy Index to server
      copy: src={{ source_file }} dest={{ dest_dir }} mode=0555

    - name: start httpd
      service: name=httpd state=started enabled=yes
