---
# tasks file for apache_deploy
- name: install httpd
  yum: name=httpd state=latest

- name: Copy Index to server
  template: src=index.j2 dest={{ dest_dir }}/index.html mode=0555
  notify: Restart httpd

- name: start httpd
  service: name=httpd state=started enabled=yes

- name: configure firewalld
  firewalld: service=http permanent=true state=enabled immediate=true
